# Version complète du code - ne pas donner celle-ci aux élèves en début de projet :-)
import utilitairesLed

def dino():
    color_1 = (0,0,0) 
    color_2 = (0, 0, 0)
    color_3 = (0, 174, 0)
    color_4 = (138, 26, 217)
    color_5 = (63, 81, 178)
    color_6 = (0, 104, 4)
    color_7 = (180, 247, 186)
    utilitairesLed.set_pixel(0,0,color_2)
    utilitairesLed.set_pixel(1,0,color_3)
    utilitairesLed.set_pixel(2,0,color_3)
    utilitairesLed.set_pixel(3,0,color_3)
    utilitairesLed.set_pixel(4,0,color_3)
    utilitairesLed.set_pixel(5,0,color_4)
    utilitairesLed.set_pixel(6,0,color_2)
    utilitairesLed.set_pixel(7,0,color_2)
    utilitairesLed.set_pixel(0,1,color_3)
    utilitairesLed.set_pixel(1,1,color_5)
    utilitairesLed.set_pixel(2,1,color_3)
    utilitairesLed.set_pixel(3,1,color_5)
    utilitairesLed.set_pixel(4,1,color_3)
    utilitairesLed.set_pixel(5,1,color_2)
    utilitairesLed.set_pixel(6,1,color_2)
    utilitairesLed.set_pixel(7,1,color_2)
    utilitairesLed.set_pixel(0,2,color_3)
    utilitairesLed.set_pixel(1,2,color_3)
    utilitairesLed.set_pixel(2,2,color_3)
    utilitairesLed.set_pixel(3,2,color_3)
    utilitairesLed.set_pixel(4,2,color_3)
    utilitairesLed.set_pixel(5,2,color_4)
    utilitairesLed.set_pixel(6,2,color_2)
    utilitairesLed.set_pixel(7,2,color_2)
    utilitairesLed.set_pixel(0,3,color_2)
    utilitairesLed.set_pixel(1,3,color_2)
    utilitairesLed.set_pixel(2,3,color_6)
    utilitairesLed.set_pixel(3,3,color_6)
    utilitairesLed.set_pixel(4,3,color_3)
    utilitairesLed.set_pixel(5,3,color_2)
    utilitairesLed.set_pixel(6,3,color_2)
    utilitairesLed.set_pixel(7,3,color_2)
    utilitairesLed.set_pixel(0,4,color_2)
    utilitairesLed.set_pixel(1,4,color_3)
    utilitairesLed.set_pixel(2,4,color_7)
    utilitairesLed.set_pixel(3,4,color_3)
    utilitairesLed.set_pixel(4,4,color_3)
    utilitairesLed.set_pixel(5,4,color_4)
    utilitairesLed.set_pixel(6,4,color_3)
    utilitairesLed.set_pixel(7,4,color_2)
    utilitairesLed.set_pixel(0,5,color_2)
    utilitairesLed.set_pixel(1,5,color_2)
    utilitairesLed.set_pixel(2,5,color_7)
    utilitairesLed.set_pixel(3,5,color_7)
    utilitairesLed.set_pixel(4,5,color_3)
    utilitairesLed.set_pixel(5,5,color_2)
    utilitairesLed.set_pixel(6,5,color_3)
    utilitairesLed.set_pixel(7,5,color_2)
    utilitairesLed.set_pixel(0,6,color_2)
    utilitairesLed.set_pixel(1,6,color_2)
    utilitairesLed.set_pixel(2,6,color_7)
    utilitairesLed.set_pixel(3,6,color_7)
    utilitairesLed.set_pixel(4,6,color_3)
    utilitairesLed.set_pixel(5,6,color_3)
    utilitairesLed.set_pixel(6,6,color_2)
    utilitairesLed.set_pixel(7,6,color_2)
    utilitairesLed.set_pixel(0,7,color_2)
    utilitairesLed.set_pixel(1,7,color_2)
    utilitairesLed.set_pixel(2,7,color_3)
    utilitairesLed.set_pixel(3,7,color_2)
    utilitairesLed.set_pixel(4,7,color_3)
    utilitairesLed.set_pixel(5,7,color_2)
    utilitairesLed.set_pixel(6,7,color_2)
    utilitairesLed.set_pixel(7,7,color_2)
    utilitairesLed.show()

def glace():
    color_1 = (0,0,0) 
    color_2 = (0, 0, 0)
    color_3 = (174, 74, 0)
    color_4 = (138, 26, 217)
    color_5 = (63, 81, 178)
    color_6 = (0, 104, 4)
    color_7 = (180, 247, 186)
    utilitairesLed.set_pixel(0,0,color_2)
    utilitairesLed.set_pixel(1,0,color_2)
    utilitairesLed.set_pixel(2,0,color_2)
    utilitairesLed.set_pixel(3,0,color_3)
    utilitairesLed.set_pixel(4,0,color_3)
    utilitairesLed.set_pixel(5,0,color_2)
    utilitairesLed.set_pixel(6,0,color_2)
    utilitairesLed.set_pixel(7,0,color_2)
    utilitairesLed.set_pixel(0,1,color_2)
    utilitairesLed.set_pixel(1,1,color_2)
    utilitairesLed.set_pixel(2,1,color_3)
    utilitairesLed.set_pixel(3,1,color_4)
    utilitairesLed.set_pixel(4,1,color_3)
    utilitairesLed.set_pixel(5,1,color_3)
    utilitairesLed.set_pixel(6,1,color_2)
    utilitairesLed.set_pixel(7,1,color_2)
    utilitairesLed.set_pixel(0,2,color_2)
    utilitairesLed.set_pixel(1,2,color_2)
    utilitairesLed.set_pixel(2,2,color_4)
    utilitairesLed.set_pixel(3,2,color_3)
    utilitairesLed.set_pixel(4,2,color_3)
    utilitairesLed.set_pixel(5,2,color_3)
    utilitairesLed.set_pixel(6,2,color_2)
    utilitairesLed.set_pixel(7,2,color_2)
    utilitairesLed.set_pixel(0,3,color_2)
    utilitairesLed.set_pixel(1,3,color_2)
    utilitairesLed.set_pixel(2,3,color_3)
    utilitairesLed.set_pixel(3,3,color_3)
    utilitairesLed.set_pixel(4,3,color_3)
    utilitairesLed.set_pixel(5,3,color_3)
    utilitairesLed.set_pixel(6,3,color_2)
    utilitairesLed.set_pixel(7,3,color_2)
    utilitairesLed.set_pixel(0,4,color_2)
    utilitairesLed.set_pixel(1,4,color_2)
    utilitairesLed.set_pixel(2,4,color_3)
    utilitairesLed.set_pixel(3,4,color_3)
    utilitairesLed.set_pixel(4,4,color_3)
    utilitairesLed.set_pixel(5,4,color_3)
    utilitairesLed.set_pixel(6,4,color_2)
    utilitairesLed.set_pixel(7,4,color_2)
    utilitairesLed.set_pixel(0,5,color_2)
    utilitairesLed.set_pixel(1,5,color_2)
    utilitairesLed.set_pixel(2,5,color_3)
    utilitairesLed.set_pixel(3,5,color_3)
    utilitairesLed.set_pixel(4,5,color_3)
    utilitairesLed.set_pixel(5,5,color_3)
    utilitairesLed.set_pixel(6,5,color_2)
    utilitairesLed.set_pixel(7,5,color_2)
    utilitairesLed.set_pixel(0,6,color_2)
    utilitairesLed.set_pixel(1,6,color_2)
    utilitairesLed.set_pixel(2,6,color_2)
    utilitairesLed.set_pixel(3,6,color_5)
    utilitairesLed.set_pixel(4,6,color_5)
    utilitairesLed.set_pixel(5,6,color_2)
    utilitairesLed.set_pixel(6,6,color_2)
    utilitairesLed.set_pixel(7,6,color_2)
    utilitairesLed.set_pixel(0,7,color_2)
    utilitairesLed.set_pixel(1,7,color_2)
    utilitairesLed.set_pixel(2,7,color_2)
    utilitairesLed.set_pixel(3,7,color_5)
    utilitairesLed.set_pixel(4,7,color_5)
    utilitairesLed.set_pixel(5,7,color_2)
    utilitairesLed.set_pixel(6,7,color_2)
    utilitairesLed.set_pixel(7,7,color_2)
    utilitairesLed.show()

def ghost():
    color_1 = (0,0,0) 
    color_2 = (0, 0, 0)
    color_3 = (43, 228, 217)
    color_4 = (0, 137, 137)
    color_5 = (0, 65, 93)
    color_6 = (46, 22, 40)
    utilitairesLed.set_pixel(0,0,color_2)
    utilitairesLed.set_pixel(1,0,color_2)
    utilitairesLed.set_pixel(2,0,color_2)
    utilitairesLed.set_pixel(3,0,color_2)
    utilitairesLed.set_pixel(4,0,color_2)
    utilitairesLed.set_pixel(5,0,color_2)
    utilitairesLed.set_pixel(6,0,color_2)
    utilitairesLed.set_pixel(7,0,color_2)
    utilitairesLed.set_pixel(0,1,color_2)
    utilitairesLed.set_pixel(1,1,color_2)
    utilitairesLed.set_pixel(2,1,color_3)
    utilitairesLed.set_pixel(3,1,color_4)
    utilitairesLed.set_pixel(4,1,color_4)
    utilitairesLed.set_pixel(5,1,color_5)
    utilitairesLed.set_pixel(6,1,color_2)
    utilitairesLed.set_pixel(7,1,color_2)
    utilitairesLed.set_pixel(0,2,color_2)
    utilitairesLed.set_pixel(1,2,color_3)
    utilitairesLed.set_pixel(2,2,color_6)
    utilitairesLed.set_pixel(3,2,color_4)
    utilitairesLed.set_pixel(4,2,color_6)
    utilitairesLed.set_pixel(5,2,color_4)
    utilitairesLed.set_pixel(6,2,color_5)
    utilitairesLed.set_pixel(7,2,color_2)
    utilitairesLed.set_pixel(0,3,color_2)
    utilitairesLed.set_pixel(1,3,color_3)
    utilitairesLed.set_pixel(2,3,color_5)
    utilitairesLed.set_pixel(3,3,color_4)
    utilitairesLed.set_pixel(4,3,color_5)
    utilitairesLed.set_pixel(5,3,color_4)
    utilitairesLed.set_pixel(6,3,color_5)
    utilitairesLed.set_pixel(7,3,color_2)
    utilitairesLed.set_pixel(0,4,color_2)
    utilitairesLed.set_pixel(1,4,color_4)
    utilitairesLed.set_pixel(2,4,color_4)
    utilitairesLed.set_pixel(3,4,color_4)
    utilitairesLed.set_pixel(4,4,color_4)
    utilitairesLed.set_pixel(5,4,color_4)
    utilitairesLed.set_pixel(6,4,color_5)
    utilitairesLed.set_pixel(7,4,color_2)
    utilitairesLed.set_pixel(0,5,color_2)
    utilitairesLed.set_pixel(1,5,color_4)
    utilitairesLed.set_pixel(2,5,color_4)
    utilitairesLed.set_pixel(3,5,color_4)
    utilitairesLed.set_pixel(4,5,color_4)
    utilitairesLed.set_pixel(5,5,color_4)
    utilitairesLed.set_pixel(6,5,color_5)
    utilitairesLed.set_pixel(7,5,color_2)
    utilitairesLed.set_pixel(0,6,color_2)
    utilitairesLed.set_pixel(1,6,color_4)
    utilitairesLed.set_pixel(2,6,color_2)
    utilitairesLed.set_pixel(3,6,color_4)
    utilitairesLed.set_pixel(4,6,color_2)
    utilitairesLed.set_pixel(5,6,color_4)
    utilitairesLed.set_pixel(6,6,color_5)
    utilitairesLed.set_pixel(7,6,color_2)
    utilitairesLed.set_pixel(0,7,color_2)
    utilitairesLed.set_pixel(1,7,color_2)
    utilitairesLed.set_pixel(2,7,color_2)
    utilitairesLed.set_pixel(3,7,color_2)
    utilitairesLed.set_pixel(4,7,color_2)
    utilitairesLed.set_pixel(5,7,color_2)
    utilitairesLed.set_pixel(6,7,color_2)
    utilitairesLed.set_pixel(7,7,color_2)
    utilitairesLed.show()